### ISSUE TITLE
castling logic incomplete;  doesn't check for castling through check

### ISSUE THREAD

**Issue by aaronfi** [jaeheonshim/ChessBoard#1]
https://github.com/jaeheonshim/ChessBoard/blob/aab7d5cf5896906e975bb620079c20fde0466adf/src/main/java/com/jaeheonshim/chessboard/piece/King.java#L105

It's illegal to castle if the square through which the king transits also happens to be under attack.

See https://github.com/aaronfi/chess-es6.js/blob/master/src/board_variation.js#L947 for one such implementation.

**Comment by jaeheonshim** [comment]
The actual logic for castling lives in the canMove()   method of king. The canCastle method performs a only a simple check to see if the code should even perform the logic checking for castling. An implementation mistake on my part.

**Comment by aaronfi** [comment]
Ah, cool.
Sorry, did a quick skim of your code, missed the canMove() method.

Cheers
