### ISSUE TITLE
En Passant doesn't seem to be implemented

### ISSUE THREAD

**Issue by jearmstrong21** [jaeheonshim/ChessBoard#2]
I looked through pawn code and I can't see where en passant is implemented.

**Comment by jaeheonshim** [comment]
Yeah, this library is still in the developmental stage and unfortunately en passant has not been implemented yet. I have it on my list of things to do, but if anyone is interested in implementing it that would be great.

**Comment by jearmstrong21** [comment]
Nice lol
Great! Good luck implementing it, I personally have no idea how I would even start.
