### ISSUE TITLE
Iterator never reaches stop condition

### ISSUE THREAD

**Issue by riadhe** [jaeheonshim/ChessBoard#4]
### Issue:
https://github.com/jaeheonshim/ChessBoard/blob/826adccfd5f2c1849bf933409747c80e22175533/src/main/java/com/jaeheonshim/chessboard/piece/Rook.java#L62-L66
In this decrementing for-loop, the iterator never reaches the stop condition. Probably a small typo that's worth pointing out.

Possibly meant? 
```java
i > end.getX()
```

**Comment by jaeheonshim** [comment]
Yep, it looks like you are correct. It also should have been `board.getSpot(i, start.getY()).getPiece()` because otherwise it will never be null.

I've fixed it in commit acd187d4. I've also added test cases to test for this so that an issue like this doesn't go unnoticed.

Thank you for your help!
