### ISSUE TITLE
How to use this for validating moves?

### ISSUE THREAD

**Issue by Samyssmile** [jaeheonshim/ChessBoard#9]
Hi, Im almost finished my chess game, what I need is to validate the moves done by player. I want to implement your lib into my game. 

Which class is my entrypoint?

**Comment by jaeheonshim** [comment]
The `ChessBoard` class would be your entry point. You basically want to set the board to the current point of your chess board, and you can validate moves by using the canMove method on the board with coordinates. If you need any more help feel free to let me know!
